### ISSUE TITLE
OSError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by hyzhak** [ContinuumIO/docker-images#83] opened 2018-04-24 08:16 UTC
I've tried to install gym and launched one of examples (`CartPole-v0`) inside of this docker but got error:

> ImportError: Library "GL" not found.

But actually I have libGL.so. So after debugging I've found that `pyglet` (which is used inside of `gym`) found the lib but just couldn't load because of error:

> OSError dlopen: cannot load any more object with static TLS

In other words `pyglet` can't load libGL.so and libGLU.so as TLS libraries because it doesn't have enough slots.

Here is the line where pyglet tries to load libGL.so and fails https://bitbucket.org/pyglet/pyglet/src/3d464716883b1a8b07a67f4932fdbe7c4af788f9/pyglet/lib.py?at=pyglet-1.3-maintenance&fileviewer=file-view-default#lib.py-137

It's well known issue with TLS `glibc`. Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793641), which is used in this docker has `glibc` with 14 slots for TLS libs only. And it would be better to increase it to 32 or even more (64) (const DTV_SURPLUS inside of `glibc-source/sysdeps/generic/ldsodefs.h`). https://github.com/openai/gym/issues/396

As well I've found few other issues related to *.so libs, which could be related:
- https://github.com/ContinuumIO/docker-images/issues/62
- https://github.com/ContinuumIO/docker-images/issues/49
- https://github.com/Kaggle/docker-python/issues/157 this container uses `continuumio/anaconda3:5.0.1` under the hood and got the same error for pytorch.

I sure this is not complete list of related issues because it is core problem which could be faced in many way. So it is quite critical.

**Comment by mbargull** [comment] 2018-05-06 11:53
The Debian issue you linked to (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793641) states that this is a `glibc <=2.21` issue.
Hence, with https://github.com/ContinuumIO/docker-images/commit/25d9d748ca99a77c253529a9f9ddea67a6e5a0de this should be fixed as the images now use `glibc 2.24`.
@hyzhak, can you confirm this is already resolved?

**Comment by pgunn** [comment] 2019-02-26 19:41
I'm running into a similar issue (not sure why it came up so recently) with some scientific software I maintain that uses conda in CI - it's dying when it imports tensorflow with

```ImportError: dlopen: cannot load any more object with static TLS```

Definitely is using libc6:amd64=2.24-11+deb9u4

**Comment by mingwandroid** [comment] 2019-02-26 19:56
Please provide reproduction steps

**Comment by pgunn** [comment] 2019-02-26 19:59
Digging at it now, was just surprised/disappointed that when I make the container manually on my workstation rather than a buildslave in our CI system, the problem did not come up.

**Comment by pgunn** [comment] 2019-02-26 20:11
Disregard this for now - this issue seems to be not entirely reproducible and I need to find out why. Might be some local issues with how we use docker.

**Comment by dbast** [comment] 2021-07-28 13:32
Not reproducible and no reproduction steps provided, thus closing. Please reopen, if this still is an issue.

**Closed by dbast** 2021-07-28 13:32 UTC
