### ISSUE TITLE
CondaMemoryError

### ISSUE THREAD

**Issue by lekhachoa** [ContinuumIO/docker-images#212] opened 2021-06-25 13:38 UTC
## Current Behavior
Error at the end Pipeline CI during installing dependency :

Preparing transaction: ...working... done
Verifying transaction: ...working... failed
**CondaMemoryError: The conda process ran out of memory. Increase system memory and/or try again.**

### Steps to Reproduce
Run conda image miniconda3 (conda ver 4.9), install some dependencies to test simple test form python, but it doesn't work:

.gitlab-ci.yaml:

```
image: continuumio/miniconda:latest
stages:
  - test
before_script:
  - conda env create -f environment.yaml
  - source activate myenv

cache:
  paths:
    - /opt/conda

test:
  stage: test
  script:
  - python3 main.py

```

enviroment.yaml file:

```
name: myenv
channels:
 - conda-forge
 - davidcaron
 - defaults
 
dependencies:
  - python==3.8
  - numpy
  - pclpy
  - pip
  - pip:
     - pymeshlab
     - pygltflib


```

## Expected Behavior
Pipeline run to the end with OK status, finished with a successful installation

## Environment Information
Run on Gitlab Docker Runner with 2GB Ram. In idle used only 700MB/2GB.

$ cat /proc/meminfo
```
MemTotal:        2041248 kB
MemFree:          815064 kB
MemAvailable:    1615984 kB
Buffers:           93572 kB
Cached:           795996 kB
SwapCached:        12228 kB
Active:           598832 kB
Inactive:         431840 kB
Active(anon):      62532 kB
Inactive(anon):    62724 kB
Active(file):     536300 kB
Inactive(file):   369116 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2095100 kB
SwapFree:        1820800 kB
```
I already check the process ram limit, but it is unlimited:

$ ulimit -Sa
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7709
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

What should I do?

**Comment by dbast** [comment] 2021-07-27 12:30
This can be reproduced by the single command: `docker run -i -t continuumio/miniconda3 /bin/bash -c "apt-get update && apt-get install time && /usr/bin/time -v conda create --name abc -c conda-forge davidcaron::pclpy python==3.8 numpy pip --dry-run"`

Output shows:
```
	Command being timed: "conda create --name abc -c conda-forge davidcaron::pclpy python==3.8 numpy pip --dry-run"
	User time (seconds): 44.18
	System time (seconds): 3.07
	Percent of CPU this job got: 94%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:50.13
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1571032
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 187
	Minor (reclaiming a frame) page faults: 760888
	Voluntary context switches: 40008
	Involuntary context switches: 2871
	Swaps: 0
	File system inputs: 41032
	File system outputs: 906840
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Maximum resident set size (kbytes): 1571032 = 1.5 GByte memory consumed by the solver, mostly caused by the dependencies of davidcaron::pclpy. So more system memory required.

Closing as this has nothing to do with the Docker Images (optimising the solver is a topic for https://github.com/conda/conda)

**Closed by dbast** 2021-07-27 12:30 UTC
