### ISSUE TITLE
Can't install anything with gcc and pip in Miniconda 4.3.27

### ISSUE THREAD

**Issue by devinXL8** [ContinuumIO/docker-images#67] opened 2017-10-02 14:20 UTC
`    unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1`

**Comment by msarahan** [comment] 2017-10-02 14:23
Duplicate of https://github.com/conda/conda/issues/6030 - please see that issue.

**Closed by msarahan** 2017-10-02 14:23 UTC
